{% set name = "citeproc-py" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citeproc_py-{{ version }}.tar.gz
  sha256: 68ecd30bb8a270f405f1020c90a48701b96796adcf1ba76c3595742377a407a4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
    - rnc2rng >=2.6.1,!=2.6.2
  run:
    - lxml
    - python

test:
  source_files:
    - tests
  imports:
    - citeproc
  commands:
    - pip check
    # nose is not compatible with Python 3.12
    - nosetests --where=tests --ignore-files=citeproc-test.py  # [py<312]
    # I think this is cleaner than patching the missing file in
    - curl https://raw.githubusercontent.com/citeproc-py/citeproc-py/2aeb25081c5ac66050ef773f81cc64e611ba517b/tests/failing_tests.txt -o tests/failing_tests.txt
    - ls -l
    - ls -l tests
    - python tests/citeproc-test.py --no-update
  requires:
    - git
    - nose
    - pip
    - curl

about:
  home: https://github.com/brechtm/citeproc-py
  summary: Citations and bibliography formatter
  license: BSD-2-Clause AND CC-BY-SA-3.0 AND MIT

  license_file:
    - LICENSE
    - LICENSE_citation-style-language_locales.md
    - LICENSE_citation-style-language_schema.txt

extra:
  recipe-maintainers:
    - mikemhenry
